backend/src/main/java/com/footalentgroup/controllers/ApiController.java, backend/src/main/java/com/footalentgroup/controllers/AuthController.java, backend/src/main/java/com/footalentgroup/controllers/EventController.java, backend/src/main/java/com/footalentgroup/models/dtos/request/EventRequestDto.java, backend/src/main/java/com/footalentgroup/models/dtos/request/TicketRequestDto.java
Se mejoró la documentación de Swagger en los controladores de Eventos, Auth y API, agregando anotaciones detalladas y validaciones en DTOs.
=> Improve Swagger documentation (Events, Auth, API)

backend/src/main/java/com/footalentgroup/services/impl/FanProfileServiceImp.java
Se corrije subida de imagenes en el metodo de actualizar perfil de fan
=> fix(backend): fixed issue preventing image upload when updating profile.

backend/src/main/java/com/footalentgroup/configuration/JwtAuthenticationFilter.java, backend/src/main/java/com/footalentgroup/controllers/FanProfileController.java
Se eliminan prints de pantalla (System.out.println)
=> Remove debug prints

backend/.env.example, backend/pom.xml, backend/src/main/java/com/footalentgroup/configuration/MailConfig.java, backend/src/main/java/com/footalentgroup/controllers/MusicianProfileController.java, backend/src/main/java/com/footalentgroup/exceptions/EmailSendingException.java, backend/src/main/java/com/footalentgroup/exceptions/GlobalExceptionHandler.java, backend/src/main/java/com/footalentgroup/models/dtos/request/ContactRequestDto.java, backend/src/main/java/com/footalentgroup/services/EmailService.java, backend/src/main/java/com/footalentgroup/services/impl/EmailServiceImpl.java, backend/src/main/resources/application.properties
Implementación del servicio de correo para permitir que los usuarios contacten a los músicos mediante JavaMailSender.
- Ve a [Google Account Security](https://myaccount.google.com/security).
- Activa la verificación en dos pasos si aún no lo hiciste.
- Busca la opción "Contraseñas de aplicaciones" y genera una nueva contraseña.
- Usa la contraseña generada en tu configuración de JavaMailSender en lugar de la contraseña de tu cuenta de Gmail.
=> Implement email service for contacting musicians

backend/src/main/java/com/footalentgroup/controllers/MusicianProfileController.java, backend/src/main/java/com/footalentgroup/models/dtos/mapper/MusicProfileMapper.java, backend/src/main/java/com/footalentgroup/models/dtos/request/MusicianProfileRequestDto.java, backend/src/main/java/com/footalentgroup/models/dtos/response/DonationResponseDto.java, backend/src/main/java/com/footalentgroup/models/entities/MusicianProfileEntity.java, backend/src/main/java/com/footalentgroup/repositories/MusicianProfileRepository.java, backend/src/main/java/com/footalentgroup/services/MusicianProfileService.java, backend/src/main/java/com/footalentgroup/services/impl/MusicianProfileServiceImpl.java
- Se agregaron nuevos atributos (alias, CBU, etc.) a la entidad de músico.
- Se creó un endpoint GET para recuperar información de donaciones vinculadas al músico.
=> Donation info

frontend/src/auth/components/ProtectedRoute.tsx, frontend/src/auth/hooks/use-required-user.ts, frontend/src/home/components/OptionsRegister.tsx, frontend/src/index.css, frontend/src/profile/EditProfilePage.tsx, frontend/src/profile/ProfilePage.tsx, frontend/src/profile/components/BannerUploader.tsx, frontend/src/profile/components/CreateEventCard.tsx, frontend/src/profile/components/MediaEmbedForm.tsx, frontend/src/profile/components/MusicUploader.tsx, frontend/src/profile/components/forms/FormFanProfile.tsx, frontend/src/profile/components/forms/FormMusicianProfile.tsx, frontend/src/profile/utils/media-utils.ts, frontend/src/providers.tsx, frontend/src/shared/hooks/use-api-mutation.ts, frontend/src/shared/ui/ScrollToTop.tsx
- Se añadió la lógica de `replace` dentro de `ProtectedRoutes` para evitar bucles de redirección cuando el usuario no está autenticado.
- Se creó el hook `useRequiredUser` para evitar el uso de optional chaining al acceder a los datos del usuario.
- Se corrigió la ruta de la fuente de la aplicación.
- Se agregaron nuevos colores al tema de TailwindCSS.
- Se implementó parcialmente la funcionalidad de la página `EditProfilePage`.
- Se añadieron props opcionales al componente `BannerUploader` para permitir la obtención de información adicional sin afectar otras implementaciones en la aplicación.
- Se corrigió un manejo innecesario de cabeceras en la instancia de `axios` dentro del hook `useApiMutation`.
- Se implementó un provider que gestiona el scroll hacia el principio de la pantalla …
=> Perfil del músico, mejoras de UX y correcciones menores

frontend/eslint.config.js, frontend/src/app/layout/Header/BackButtonHeader.tsx, frontend/src/auth/components/UserMenu.tsx, frontend/src/profile/hooks/use-media-embed.ts, frontend/src/profile/musician/EditProfileMusicianPage.tsx, frontend/src/profile/musician/components/MediaEmbedForm.tsx, frontend/src/profile/musician/components/MusicUploader.tsx, frontend/src/profile/utils/media-utils.ts, frontend/src/shared/utils/axios-instance.ts
- Se implementó el llamado al backend para realizar la correcta subida de música.
- Se eliminó el código comentado innecesario.
- Se actualizaron los enlaces (`Links`) a las rutas correspondientes de la aplicación.
=> Implementacion de llamadas al Backend y arreglo de redireccionamiento

backend/src/main/java/com/footalentgroup/models/dtos/mapper/SongMapper.java, backend/src/main/java/com/footalentgroup/models/dtos/response/DonationResponseDto.java, backend/src/main/java/com/footalentgroup/models/dtos/response/MusicianInfoResponseDto.java, backend/src/main/java/com/footalentgroup/models/dtos/response/SongResponseDto.java, backend/src/main/java/com/footalentgroup/repositories/MusicianProfileRepository.java, backend/src/main/java/com/footalentgroup/services/impl/MusicianFollowsServiceImlp.java, backend/src/main/java/com/footalentgroup/services/impl/SongServiceImpl.java
- **MusicianInfoResponseDto**: Ahora incluye el ID del artista/banda.
- **DonationResponseDto**: Se modifica la imagen retornada, ahora se envía la foto de perfil del artista/banda en lugar del banner.
=> Return ID in MusicianInfoResponseDto & photoUrl in DonationResponseDto

backend/src/main/java/com/footalentgroup/models/dtos/mapper/SongMapper.java, backend/src/main/java/com/footalentgroup/models/dtos/response/MusicianInfoResponseDto.java
Añadir la foto de perfil de usuario a la informacion de la respuesta de canciones
=> feat(backend): add photoUrl field to song information

frontend/src/profile/components/forms/components/labeledFields/LabeledInput.tsx, frontend/src/profile/components/forms/components/labeledFields/LabeledSelect.tsx, frontend/src/profile/components/forms/components/sections/PersonalDataMusicianSection.tsx, frontend/src/profile/components/forms/shemas/ProfileSchema.ts, frontend/src/profile/hooks/use-load-musician-form.ts, frontend/src/profile/utils/handlers/handle-musician-profile-submit.ts
Este PR agrega un nuevo campo de "Descripción" al formulario de músico, haciendo que sea un campo requerido. Además, se ajustaron los estilos generales del formulario para asegurar que el diseño sea similar con el prototipo de Figma.
Cambios realizados
- Se añadió el campo de descripción al formulario de músico, marcándolo como requerido.
- Se modifica el handle-musician-profile-sumbit y use-load-musician para la carga y actualización de dicho campo. 
- Se añade validación para la textarea descripción al formMusicianProfileSchema. 
- Ajustes en los estilos de los elementos del formulario para asegurar que se sea similiar con el diseño de Figma.
=> Campo descripción requerido en el formulario del músico y estilos generales del formulario. 

frontend/src/auth/components/UserMenu.tsx, frontend/src/auth/components/ui/UserProfileIcon.tsx, frontend/src/profile/components/forms/FormFanProfile.tsx, frontend/src/profile/fan/components/FavoriteSongList.tsx, frontend/src/profile/musician/ProfileMusicianPage.tsx, frontend/src/routes/index.tsx
- Se modifica el UserMenu para ajustar los botones disponibles según el rol del usuario, cambiando también las rutas de acceso correspondientes.
- Se crea el componente UserProfileIcon utilizado en el botón "Mi perfil".
- Se corrige FavoriteSongList para que no muestre contenido si no hay canciones marcadas como favoritas.
- Se modifica el archivo index para que la ruta /profile/fan incluya el id.
- Se agrega validación de existencia de items antes de acceder a sus propiedades en ProfileMusicianPage, evitando errores de ejecución cuando no hay datos.
=> Mejoras de navegación, validaciones y menú según rol de usuario. 

frontend/src/app/layout/Header/Header.tsx, frontend/src/profile/fan/DonationModal.tsx, frontend/src/profile/fan/components/CardSong.tsx, frontend/src/profile/fan/ui/PauseIcon.tsx, frontend/src/profile/musician/ProfileMusicianPage.tsx, frontend/src/profile/musician/components/DonateSection.tsx, frontend/src/profile/musician/musician-types.ts
- Se agrego el poder agregar el tema del musico a favoritos entrando a su perfil como fan
- Tambien se agrego el manejo del modal para donar desde el perfil del músico
- Se arreglaron los estilos de las imagenes, para que mantenga un aspect-ratio 1:1
- Se modifico el menu de mobile para que no aparezca el boton de iniciar sesión al haber un usuario autenticado
=> Lógica de favoritos y donacion en el perfil del músico y mejoras en los estilos de las imagenes

frontend/src/auth/components/LoginForm.tsx, frontend/src/auth/components/RegistrationForm.tsx, frontend/src/auth/components/UserMenu.tsx, frontend/src/event/components/step/StepFour.tsx, frontend/src/profile/components/forms/FormMusicianProfile.tsx, frontend/src/profile/musician/EditProfileMusicianPage.tsx, frontend/src/profile/musician/ProfileMusicianPage.tsx, frontend/src/profile/musician/components/ContactForm.tsx, frontend/src/profile/musician/components/DonateSection.tsx, frontend/src/profile/musician/components/FollowArtist.tsx, frontend/src/profile/musician/musician-types.ts, frontend/src/shared/components/Cards/EventCard.tsx
- Se quitó console.logs y código comentado
- Se implemento la llamada al backend de eventos, para mostarlos en el perfil del músico
- Se implemento la funcionalidad del formulario de contacto del músico
- Se corrigieron algunos estilos generales
=> Limpieza de codigo e implementacion de eventos y contacto al músico

frontend/src/profile/musician/ProfileMusicianPage.tsx
Se corrigió un error al intentar pedir datos de un usuario, cuando este puede no estar autenticado en una ruta que dejo de estar protegida
=> Fix: error al visitar el profile del músico como invitado

frontend/src/app/layout/Header/Header.tsx, frontend/src/home/components/FeaturedTopicsList.tsx, frontend/src/home/components/sections/DiscoverArtist.tsx, frontend/src/home/components/sections/FAQList.tsx, frontend/src/home/components/sections/FeaturedArtists.tsx, frontend/src/home/components/sections/UpcomingEvents.tsx, frontend/src/shared/components/QuestionsAccordion.tsx
Este PR implementa los cambios indicados en Figma para los enlaces del `Header` y el menú desplegable. Se actualizaron los enlaces para dirigir correctamente a las secciones correspondientes en la `HomePage`, asegurando una navegación fluida y precisa.  
Además, se trabajó en la mejora del icono del menú desplegable: ahora, cuando el menú está abierto, el icono cambia a una `X` para una mejor experiencia visual y usabilidad.  
- Se actualizaron los enlaces del `Header` según las especificaciones de Figma.  
- Se enlazaron correctamente los enlaces con sus respectivas secciones dentro de la `HomePage`.  
- Se modificó el comportamiento del icono del menú desplegable para que cambie a una `X` cuando está abierto.  
1. Iniciar el proyecto localmente.  
2. Probar los enlaces del `Header` y el …
=>  Actualización de enlaces en el Header y mejoras en el menú desplegable  

backend/src/main/java/com/footalentgroup/models/dtos/mapper/EventMapper.java, backend/src/main/java/com/footalentgroup/models/dtos/response/EventSimpleResponseDto.java
- Se agregó la información relevante del artista/banda a la información de los eventos.
=> Add musician info to EventSimpleResponseDto

frontend/src/event/EventPage.tsx, frontend/src/event/components/step/StepFour.tsx, frontend/src/event/components/step/StepTwo.tsx
Se cambio el requerimiento obligatiro al cargar la imagen en /event.
quedo de forma obcional
=> Gino gallardo

frontend/src/event/components/step/StepFour.tsx, frontend/src/event/components/ui/CalendarButton.tsx
el cual da funcioanlidad al boton agregara calendario en el StepFour.
tambien se actualizo el renderizado de los tickets, para que muestre las opciones que ingrese el usuario.
=> update: se creo componente CalendarButton

frontend/src/profile/musician/components/FollowArtist.tsx
- Se corrige la verificación lógica para mostrar la sección solo si hay al menos un enlace válido.
- Ahora solo se muestran los enlaces que corresponden al músico.
=> Mejorar lógica de enlaces de músicos

frontend/src/app/ui/Spinner.tsx, frontend/src/profile/components/DonateButton.tsx, frontend/src/profile/components/HeartButton.tsx, frontend/src/profile/musician/ProfileMusicianPage.tsx, frontend/src/profile/musician/components/MediaSkeleton.tsx, frontend/src/shared/components/Cards/EventCard.tsx
- Se mejoraron los estilos del perfil del músico
- Se agregaron redireccionamientos al hacer click en los skeletons del músico
- Se creo el componente Spinner para utilizar en estados de carga
=> Responsive del perfil del músico y Spinner

frontend/src/index.css, frontend/src/profile/components/HeartButton.tsx, frontend/src/profile/fan/components/FavoriteSongList.tsx, frontend/src/profile/musician/ProfileMusicianPage.tsx, frontend/src/profile/types/favorite-songs.ts, frontend/src/shared/hooks/use-api-query.ts
- Animación y lógica al botón de guardar una canción.
- Validación de roles y autenticación en los botones de guardar y donar.
=> Mejoras en botones de guardar y donar

frontend/src/home/components/sections/BannerGuitarsRegister.tsx, frontend/src/shared/components/Cards/OptionsRegisterCards.tsx
Este PR implementa mejoras en la funcionalidad de los botones en `OptionsRegisterCards`, asegurando que:
- **El botón "Explorar"** utilice `<Link>` de `react-router` para redireccionar correctamente a `/explorer`.
- **El botón "Registrar"** continúe abriendo el modal de autenticación como antes.
Además, se realizaron mejoras de **accesibilidad y estilos** en `BannerGuitarsRegister`, optimizando la experiencia de usuario.
- Refactorización del botón dentro de `OptionsRegisterCards` para diferenciar `"Explorar"` y `"Registrar"`.
- Implementación de `<Link>` para la opción `"Explorar"` en lugar de `onClick`.
- Conservación de la funcionalidad de apertura del modal en `"Registrar"`.
- **Mejoras en accesibilidad**:
- Ajuste en el contraste de colores para mejor visibilidad.
- Inclusión de …
=> Mejora en la funcionalidad y accesibilidad de botones en `OptionsRegisterCards` y `BannerGuitarsRegister`

frontend/src/app/ui/Button.tsx, frontend/src/index.css
Se actualizó el componente `Button` para garantizar la coherencia visual con todos los botones de la página, siguiendo las especificaciones de Figma.
- Se agregó la propiedad cursor-pointer para mejorar la interacción en el efecto hover.
- Se corrigieron los colores del texto según las especificaciones del diseño en Figma.
- **No** se añadió el color de fondo en el efecto hover, ya que se está a la espera de confirmación por parte del equipo de diseño.
=> Ajuste de estilos en Button para alineación con el diseño

frontend/src/app/layout/Footer/Footer.tsx, frontend/src/profile/musician/ProfileMusicianPage.tsx, frontend/src/profile/musician/components/DonateSection.tsx
- Se agrego renderizado condicional en el perfil del músico para componentes que no deberian verse al ser el dueño del perfil
- A los Skeletons se les agrego un texto condicional y redireccionamiento si es el dueño o no del perfil
=> Renderizado de componentes en base al ID del usuario identificado con el ID de la URL

frontend/src/app/components/MusicSearch.tsx, frontend/src/app/layout/Header/Header.tsx, frontend/src/app/ui/Input.tsx, frontend/src/index.css, frontend/src/profile/fan/ProfileFanPage.tsx
- Se corrigieron los estilos del componente Input para que no interfieran con LabeledInput ni con el input del buscador.
- Se eliminó la propiedad 100vw del main en index.css.
- Se ajustó el ancho del contenedor en ProfileFanPage para asegurar que todo su contenido sea visible correctamente.
=> Corregir estilos de Input, quitar 100vw del main y ajustar ancho en ProfileFanPage

frontend/src/auth/components/AuthModal.tsx, frontend/src/auth/components/LoginForm.tsx, frontend/src/auth/components/RegistrationForm.tsx, frontend/src/auth/components/RoleSelector.tsx, frontend/src/auth/components/WelcomeUserModal.tsx
Se realizaron ajustes de estilos en los siguientes componentes, alineándolos con el diseño en Figma y corrigiendo errores ortográficos:
- Login
- Registro
- Modal de bienvenida
=> Ajuste de estilos en Login & Registro

frontend/src/app/ui/NotFound.tsx, frontend/src/routes/index.tsx
Se crea la página 404 para manejar rutas no encontradas.
=> Página 404

frontend/src/app/components/EventById.tsx, frontend/src/home/components/sections/Hero.tsx
- Se actualizaron los estilos del Hero para respetar el diseño del figma
- Se actualizo la lógica de los botones en base al rol y se arreglo el scroll del boton "Explorar"
- Se ajusto el padding del componente EventById para el responsive
=> Actualizacion del componente Hero en Home

frontend/src/shared/components/Cards/EventCard.tsx
- Se ajustaron los estilos del componente `EventCard`, alineándolo con el diseño en Figma.
- Se mejoró la estructura HTML para mayor consistencia y accesibilidad.
=> Ajuste de estilos y estructura en tarjetas de Eventos

frontend/src/index.css, frontend/src/profile/fan/ProfileFanPage.tsx, frontend/src/profile/fan/components/CardSong.tsx, frontend/src/profile/fan/components/FavoriteSongList.tsx, frontend/src/profile/fan/ui/CloseIcon.tsx
- Se modificaron los estilos de la sección FavoriteSongList y de sus componentes CardSong dentro de la página PageFanProfile para que coincidan con el diseño definido en Figma.
- Además, se eliminó la sección TemasDestacados de PageFanProfile.
=> Fan Profile: eliminación de temas destacados y modificación de estilos de FavoriteSongList

frontend/src/auth/components/ForgotPasswordForm.tsx, frontend/src/auth/context/AuthProvider.tsx, frontend/src/profile/fan/components/CardSong.tsx, frontend/src/profile/fan/components/LabeledFieldReadOnly.tsx
Se eliminaron todos los `console.log` y `console.error` del código.
=> Eliminar prints de consola y mensajes de debug

frontend/src/app/components/CardArtist.tsx, frontend/src/app/components/EventById.tsx, frontend/src/app/components/MusicSearch.tsx, frontend/src/app/layout/Header/Header.tsx, frontend/src/event/components/step/StepFour.tsx, frontend/src/event/components/step/StepOne.tsx, frontend/src/event/components/step/StepTwo.tsx, frontend/src/home/components/CardSong.tsx, frontend/src/home/components/FeaturedSongs.tsx, frontend/src/profile/components/forms/components/sections/ContactDetailsMusicianSection.tsx
Se actualizaron y mejoraron los textos en varios componentes.
=> Ajuste de textos
